"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python
$character
"""

[fill]
symbol=" "

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"